site_name: Wire
repo_name: Wire
repo_url: https://github.com/square/wire
site_description: "gRPC and protocol buffers for Android, Kotlin, and Java."
site_author: Square, Inc.
remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Square, Inc.'

theme:
  name: 'material'
  favicon: images/icon-square.png
  logo: images/icon-square.png
  palette:
    primary: 'blue'
    accent: 'white'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - 'Gradle Plugin': wire_compiler.md
  - 'gRPC': wire_grpc.md
  - 'Stack Overflow ⏏': https://stackoverflow.com/questions/tagged/wire?sort=active
  - '3.x API':
    - 'wire-grpc-client': 3.x/wire-grpc-client/com.squareup.wire/index.md
    - 'wire-moshi-adapter': 3.x/wire-moshi-adapter/com.squareup.wire/index.md
    - 'wire-runtime': 3.x/wire-runtime/com.squareup.wire/index.md
  - '2.x API':
    - 'wire-gson-support ⏏': https://square.github.io/wire/2.x/wire-gson-support/
    - 'wire-runtime ⏏': https://square.github.io/wire/2.x/wire-runtime/
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md
  - 'Protocol Buffers ⏏': https://developers.google.com/protocol-buffers/docs/proto

