// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/google/protobuf/descriptor.proto at 380:1
package com.google.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class EnumOptions extends Message<EnumOptions, EnumOptions.Builder> {
  public static final ProtoAdapter<EnumOptions> ADAPTER = new ProtoAdapter<EnumOptions>(FieldEncoding.LENGTH_DELIMITED, EnumOptions.class) {
    @Override
    public int encodedSize(EnumOptions value) {
      return UninterpretedOption.ADAPTER.asRepeated().encodedSizeWithTag(999, value.uninterpreted_option)
          + (value.enum_option != null ? ProtoAdapter.BOOL.encodedSizeWithTag(71000, value.enum_option) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, EnumOptions value) throws IOException {
      if (value.uninterpreted_option != null) UninterpretedOption.ADAPTER.asRepeated().encodeWithTag(writer, 999, value.uninterpreted_option);
      if (value.enum_option != null) ProtoAdapter.BOOL.encodeWithTag(writer, 71000, value.enum_option);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public EnumOptions decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 999: builder.uninterpreted_option.add(UninterpretedOption.ADAPTER.decode(reader)); break;
          case 71000: builder.enum_option(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public EnumOptions redact(EnumOptions value) {
      Builder builder = value.newBuilder();
      redactElements(builder.uninterpreted_option, UninterpretedOption.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  };

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_ENUM_OPTION = false;

  /**
   * The parser stores options it doesn't recognize here. See above.
   */
  public final List<UninterpretedOption> uninterpreted_option;

  public final Boolean enum_option;

  public EnumOptions(List<UninterpretedOption> uninterpreted_option, Boolean enum_option) {
    this(uninterpreted_option, enum_option, ByteString.EMPTY);
  }

  public EnumOptions(List<UninterpretedOption> uninterpreted_option, Boolean enum_option, ByteString unknownFields) {
    super(unknownFields);
    this.uninterpreted_option = immutableCopyOf(uninterpreted_option);
    this.enum_option = enum_option;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uninterpreted_option = copyOf(uninterpreted_option);
    builder.enum_option = enum_option;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EnumOptions)) return false;
    EnumOptions o = (EnumOptions) other;
    return equals(unknownFields(), o.unknownFields())
        && equals(uninterpreted_option, o.uninterpreted_option)
        && equals(enum_option, o.enum_option);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uninterpreted_option != null ? uninterpreted_option.hashCode() : 1);
      result = result * 37 + (enum_option != null ? enum_option.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uninterpreted_option != null) builder.append(", uninterpreted_option=").append(uninterpreted_option);
    if (enum_option != null) builder.append(", enum_option=").append(enum_option);
    return builder.replace(0, 2, "EnumOptions{").append('}').toString();
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<EnumOptions, Builder> {
    public List<UninterpretedOption> uninterpreted_option;

    public Boolean enum_option;

    public Builder() {
      uninterpreted_option = newMutableList();
    }

    /**
     * The parser stores options it doesn't recognize here. See above.
     */
    public Builder uninterpreted_option(List<UninterpretedOption> uninterpreted_option) {
      checkElementsNotNull(uninterpreted_option);
      this.uninterpreted_option = uninterpreted_option;
      return this;
    }

    public Builder enum_option(Boolean enum_option) {
      this.enum_option = enum_option;
      return this;
    }

    @Override
    public EnumOptions build() {
      return new EnumOptions(uninterpreted_option, enum_option, buildUnknownFields());
    }
  }
}
