// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/google/protobuf/descriptor.proto at 389:1
package com.google.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import com.squareup.wire.protos.custom_options.FooBar;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.util.List;
import okio.ByteString;

public final class EnumValueOptions extends Message<EnumValueOptions> {
  public static final ProtoAdapter<EnumValueOptions> ADAPTER = ProtoAdapter.newMessageAdapter(EnumValueOptions.class);

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ENUM_VALUE_OPTION = 0;

  public static final Boolean DEFAULT_FOREIGN_ENUM_VALUE_OPTION = false;

  /**
   * The parser stores options it doesn't recognize here. See above.
   */
  @WireField(
      tag = 999,
      adapter = "com.google.protobuf.UninterpretedOption#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<UninterpretedOption> uninterpreted_option;

  @WireField(
      tag = 70000,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer enum_value_option;

  @WireField(
      tag = 70001,
      adapter = "com.squareup.wire.protos.custom_options.FooBar$More#ADAPTER"
  )
  public final FooBar.More complex_enum_value_option;

  @WireField(
      tag = 70002,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean foreign_enum_value_option;

  public EnumValueOptions(List<UninterpretedOption> uninterpreted_option, Integer enum_value_option, FooBar.More complex_enum_value_option, Boolean foreign_enum_value_option) {
    this(uninterpreted_option, enum_value_option, complex_enum_value_option, foreign_enum_value_option, ByteString.EMPTY);
  }

  public EnumValueOptions(List<UninterpretedOption> uninterpreted_option, Integer enum_value_option, FooBar.More complex_enum_value_option, Boolean foreign_enum_value_option, ByteString unknownFields) {
    super(unknownFields);
    this.uninterpreted_option = immutableCopyOf(uninterpreted_option);
    this.enum_value_option = enum_value_option;
    this.complex_enum_value_option = complex_enum_value_option;
    this.foreign_enum_value_option = foreign_enum_value_option;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uninterpreted_option = copyOf(uninterpreted_option);
    builder.enum_value_option = enum_value_option;
    builder.complex_enum_value_option = complex_enum_value_option;
    builder.foreign_enum_value_option = foreign_enum_value_option;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EnumValueOptions)) return false;
    EnumValueOptions o = (EnumValueOptions) other;
    return equals(unknownFields(), o.unknownFields())
        && equals(uninterpreted_option, o.uninterpreted_option)
        && equals(enum_value_option, o.enum_value_option)
        && equals(complex_enum_value_option, o.complex_enum_value_option)
        && equals(foreign_enum_value_option, o.foreign_enum_value_option);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uninterpreted_option != null ? uninterpreted_option.hashCode() : 1);
      result = result * 37 + (enum_value_option != null ? enum_value_option.hashCode() : 0);
      result = result * 37 + (complex_enum_value_option != null ? complex_enum_value_option.hashCode() : 0);
      result = result * 37 + (foreign_enum_value_option != null ? foreign_enum_value_option.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<EnumValueOptions, Builder> {
    public List<UninterpretedOption> uninterpreted_option;

    public Integer enum_value_option;

    public FooBar.More complex_enum_value_option;

    public Boolean foreign_enum_value_option;

    public Builder() {
      uninterpreted_option = newMutableList();
    }

    /**
     * The parser stores options it doesn't recognize here. See above.
     */
    public Builder uninterpreted_option(List<UninterpretedOption> uninterpreted_option) {
      checkElementsNotNull(uninterpreted_option);
      this.uninterpreted_option = uninterpreted_option;
      return this;
    }

    public Builder enum_value_option(Integer enum_value_option) {
      this.enum_value_option = enum_value_option;
      return this;
    }

    public Builder complex_enum_value_option(FooBar.More complex_enum_value_option) {
      this.complex_enum_value_option = complex_enum_value_option;
      return this;
    }

    public Builder foreign_enum_value_option(Boolean foreign_enum_value_option) {
      this.foreign_enum_value_option = foreign_enum_value_option;
      return this;
    }

    @Override
    public EnumValueOptions build() {
      return new EnumValueOptions(uninterpreted_option, enum_value_option, complex_enum_value_option, foreign_enum_value_option, buildUnknownFields());
    }
  }
}
