// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/google/protobuf/descriptor.proto at 51:1
package com.google.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import java.lang.Object;
import java.lang.Override;
import java.util.List;
import okio.ByteString;

/**
 * The protocol compiler can output a FileDescriptorSet containing the .proto
 * files it parses.
 */
public final class FileDescriptorSet extends Message<FileDescriptorSet, FileDescriptorSet.Builder> {
  public static final ProtoAdapter<FileDescriptorSet> ADAPTER = ProtoAdapter.newMessageAdapter(FileDescriptorSet.class);

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.google.protobuf.FileDescriptorProto#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<FileDescriptorProto> file;

  public FileDescriptorSet(List<FileDescriptorProto> file) {
    this(file, ByteString.EMPTY);
  }

  public FileDescriptorSet(List<FileDescriptorProto> file, ByteString unknownFields) {
    super(unknownFields);
    this.file = immutableCopyOf(file);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.file = copyOf(file);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FileDescriptorSet)) return false;
    FileDescriptorSet o = (FileDescriptorSet) other;
    return equals(unknownFields(), o.unknownFields())
        && equals(file, o.file);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (file != null ? file.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<FileDescriptorSet, Builder> {
    public List<FileDescriptorProto> file;

    public Builder() {
      file = newMutableList();
    }

    public Builder file(List<FileDescriptorProto> file) {
      checkElementsNotNull(file);
      this.file = file;
      return this;
    }

    @Override
    public FileDescriptorSet build() {
      return new FileDescriptorSet(file, buildUnknownFields());
    }
  }
}
