// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: service_kotlin.proto
package com.squareup.wire.protos.kotlin

import com.squareup.wire.Service
import com.squareup.wire.WireRpc

interface SomeServiceClient : Service {
  @WireRpc(
    path = "/squareup.protos.kotlin.SomeService/SomeMethod",
    requestAdapter = "squareup.protos.kotlin.SomeRequest#ADAPTER",
    responseAdapter = "squareup.protos.kotlin.SomeResponse#ADAPTER"
  )
  suspend fun SomeMethod(request: SomeRequest): SomeResponse
}
