// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/redacted_test.proto at 22:1
package com.squareup.wire.protos.redacted;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import okio.ByteString;

public final class NotRedacted extends Message<NotRedacted, NotRedacted.Builder> {
  public static final ProtoAdapter<NotRedacted> ADAPTER = ProtoAdapter.newMessageAdapter(NotRedacted.class);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_A = "";

  public static final String DEFAULT_B = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String a;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String b;

  public NotRedacted(String a, String b) {
    this(a, b, ByteString.EMPTY);
  }

  public NotRedacted(String a, String b, ByteString unknownFields) {
    super(unknownFields);
    this.a = a;
    this.b = b;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.a = a;
    builder.b = b;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NotRedacted)) return false;
    NotRedacted o = (NotRedacted) other;
    return equals(unknownFields(), o.unknownFields())
        && equals(a, o.a)
        && equals(b, o.b);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (a != null ? a.hashCode() : 0);
      result = result * 37 + (b != null ? b.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<NotRedacted, Builder> {
    public String a;

    public String b;

    public Builder() {
    }

    public Builder a(String a) {
      this.a = a;
      return this;
    }

    public Builder b(String b) {
      this.b = b;
      return this;
    }

    @Override
    public NotRedacted build() {
      return new NotRedacted(a, b, buildUnknownFields());
    }
  }
}
