// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/redacted_test.proto at 65:1
package com.squareup.wire.protos.redacted;

import com.google.protobuf.FieldOptions;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import okio.ByteString;

public final class RedactedExtension extends Message<RedactedExtension> {
  public static final ProtoAdapter<RedactedExtension> ADAPTER = ProtoAdapter.newMessageAdapter(RedactedExtension.class);

  private static final long serialVersionUID = 0L;

  public static final FieldOptions FIELD_OPTIONS_D = new FieldOptions.Builder()
      .redacted(true)
      .build();

  public static final String DEFAULT_D = "";

  public static final String DEFAULT_E = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      redacted = true
  )
  public final String d;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String e;

  public RedactedExtension(String d, String e) {
    this(d, e, ByteString.EMPTY);
  }

  public RedactedExtension(String d, String e, ByteString unknownFields) {
    super(unknownFields);
    this.d = d;
    this.e = e;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.d = d;
    builder.e = e;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RedactedExtension)) return false;
    RedactedExtension o = (RedactedExtension) other;
    return equals(unknownFields(), o.unknownFields())
        && equals(d, o.d)
        && equals(e, o.e);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (d != null ? d.hashCode() : 0);
      result = result * 37 + (e != null ? e.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<RedactedExtension, Builder> {
    public String d;

    public String e;

    public Builder() {
    }

    public Builder d(String d) {
      this.d = d;
      return this;
    }

    public Builder e(String e) {
      this.e = e;
      return this;
    }

    @Override
    public RedactedExtension build() {
      return new RedactedExtension(d, e, buildUnknownFields());
    }
  }
}
