// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.kotlin.unknownfields.NestedVersionOne in unknown_fields.proto
import Foundation
import Wire

public struct NestedVersionOne {

    public var i: Int32?
    public var unknownFields: Wire.UnknownFields = .init()

    public init(i: Int32? = nil) {
        self.i = i
    }

}

#if !WIRE_REMOVE_EQUATABLE
extension NestedVersionOne : Equatable {
}
#endif

#if !WIRE_REMOVE_HASHABLE
extension NestedVersionOne : Hashable {
}
#endif

#if swift(>=5.5)
extension NestedVersionOne : Sendable {
}
#endif

extension NestedVersionOne : ProtoMessage {

    public static func protoMessageTypeURL() -> Swift.String {
        return "type.googleapis.com/squareup.protos.kotlin.unknownfields.NestedVersionOne"
    }

}

extension NestedVersionOne : Proto2Codable {

    public init(from reader: Wire.ProtoReader) throws {
        var i: Swift.Int32? = nil

        let token = try reader.beginMessage()
        while let tag = try reader.nextTag(token: token) {
            switch tag {
            case 1: i = try reader.decode(Swift.Int32.self)
            default: try reader.readUnknownField(tag: tag)
            }
        }
        self.unknownFields = try reader.endMessage(token: token)

        self.i = i
    }

    public func encode(to writer: Wire.ProtoWriter) throws {
        try writer.encode(tag: 1, value: self.i)
        try writer.writeUnknownFields(unknownFields)
    }

}

#if !WIRE_REMOVE_CODABLE
extension NestedVersionOne : Codable {

    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: Wire.StringLiteralCodingKeys.self)
        self.i = try container.decodeIfPresent(Swift.Int32.self, forKey: "i")
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var container = encoder.container(keyedBy: Wire.StringLiteralCodingKeys.self)

        try container.encodeIfPresent(self.i, forKey: "i")
    }

}
#endif
