// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.kotlin.foreign.ForeignMessage in foreign.proto
import Foundation
import Wire

public struct ForeignMessage {

    @ProtoDefaulted
    public var i: Int32?
    public var unknownFields: Foundation.Data = .init()

    public init(configure: (inout Self) -> Swift.Void = { _ in }) {
        configure(&self)
    }

}

#if !WIRE_REMOVE_EQUATABLE
extension ForeignMessage : Equatable {
}
#endif

#if !WIRE_REMOVE_HASHABLE
extension ForeignMessage : Hashable {
}
#endif

#if swift(>=5.5)
extension ForeignMessage : Sendable {
}
#endif

extension ForeignMessage : ProtoDefaultedValue {

    public static var defaultedValue: ForeignMessage {
        ForeignMessage()
    }
}

extension ForeignMessage : ProtoMessage {

    public static func protoMessageTypeURL() -> Swift.String {
        return "type.googleapis.com/squareup.protos.kotlin.foreign.ForeignMessage"
    }

}

extension ForeignMessage : Proto2Codable {

    public init(from protoReader: Wire.ProtoReader) throws {
        var i: Swift.Int32? = nil

        let token = try protoReader.beginMessage()
        while let tag = try protoReader.nextTag(token: token) {
            switch tag {
            case 1: i = try protoReader.decode(Swift.Int32.self)
            default: try protoReader.readUnknownField(tag: tag)
            }
        }
        self.unknownFields = try protoReader.endMessage(token: token)

        self._i.wrappedValue = i
    }

    public func encode(to protoWriter: Wire.ProtoWriter) throws {
        try protoWriter.encode(tag: 1, value: self.i)
        try protoWriter.writeUnknownFields(unknownFields)
    }

}

#if !WIRE_REMOVE_CODABLE
extension ForeignMessage : Codable {

    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: Wire.StringLiteralCodingKeys.self)
        self._i.wrappedValue = try container.decodeIfPresent(Swift.Int32.self, forKey: "i")
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var container = encoder.container(keyedBy: Wire.StringLiteralCodingKeys.self)

        try container.encodeIfPresent(self.i, forKey: "i")
    }

}
#endif
