//
//  Copyright © 2020 Square Inc. All rights reserved.
//

import Foundation

/**
 A class responsible for turning an in-memory struct generated by the Wire
 code generator into serialized bytes in the protocol buffer format that 
 represent that struct.

 General usage will look something like:
 ```
 let encoder = ProtoEncoder()
 let data = try encoder.encode(generatedMessageInstance)
 ```
 */
public final class ProtoEncoder {

    // MARK: - Initialization

    public init() {}

    // MARK: - Public Methods

    public func encode<T: ProtoEncodable>(_ value: T) throws -> Data {
        fatalError("TODO")
    }

}
