// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/custom_options.proto
package com.squareup.wire.protos.custom_options;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.FLOAT;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT64;

public final class FooBar extends Message {

  public static final Integer DEFAULT_FOO = 0;
  public static final String DEFAULT_BAR = "";
  public static final Nested DEFAULT_BAZ = getDefaultInstance(Nested.class);
  public static final Long DEFAULT_QUX = 0L;
  public static final Float DEFAULT_FRED = 0F;
  public static final Double DEFAULT_DAISY = 0D;

  @ProtoField(tag = 1, type = INT32)
  public final Integer foo;

  @ProtoField(tag = 2, type = STRING)
  public final String bar;

  @ProtoField(tag = 3)
  public final Nested baz;

  @ProtoField(tag = 4, type = UINT64)
  public final Long qux;

  @ProtoField(tag = 5, type = FLOAT)
  public final Float fred;

  @ProtoField(tag = 6, type = DOUBLE)
  public final Double daisy;

  private FooBar(Builder builder) {
    super(builder);
    this.foo = builder.foo;
    this.bar = builder.bar;
    this.baz = builder.baz;
    this.qux = builder.qux;
    this.fred = builder.fred;
    this.daisy = builder.daisy;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FooBar)) return false;
    FooBar o = (FooBar) other;
    return equals(foo, o.foo)
        && equals(bar, o.bar)
        && equals(baz, o.baz)
        && equals(qux, o.qux)
        && equals(fred, o.fred)
        && equals(daisy, o.daisy);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = foo != null ? foo.hashCode() : 0;
      result = result * 37 + (bar != null ? bar.hashCode() : 0);
      result = result * 37 + (baz != null ? baz.hashCode() : 0);
      result = result * 37 + (qux != null ? qux.hashCode() : 0);
      result = result * 37 + (fred != null ? fred.hashCode() : 0);
      result = result * 37 + (daisy != null ? daisy.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FooBar> {

    public Integer foo;
    public String bar;
    public Nested baz;
    public Long qux;
    public Float fred;
    public Double daisy;

    public Builder() {
    }

    public Builder(FooBar message) {
      super(message);
      if (message == null) return;
      this.foo = message.foo;
      this.bar = message.bar;
      this.baz = message.baz;
      this.qux = message.qux;
      this.fred = message.fred;
      this.daisy = message.daisy;
    }

    public Builder foo(Integer foo) {
      this.foo = foo;
      return this;
    }

    public Builder bar(String bar) {
      this.bar = bar;
      return this;
    }

    public Builder baz(Nested baz) {
      this.baz = baz;
      return this;
    }

    public Builder qux(Long qux) {
      this.qux = qux;
      return this;
    }

    public Builder fred(Float fred) {
      this.fred = fred;
      return this;
    }

    public Builder daisy(Double daisy) {
      this.daisy = daisy;
      return this;
    }

    @Override
    public FooBar build() {
      return new FooBar(this);
    }
  }

  public static final class Nested extends Message {

    public static final FooBarBazEnum DEFAULT_VALUE = FooBarBazEnum.FOO;

    @ProtoField(tag = 1, type = ENUM)
    public final FooBarBazEnum value;

    private Nested(Builder builder) {
      super(builder);
      this.value = builder.value;
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof Nested)) return false;
      return equals(value, ((Nested) other).value);
    }

    @Override
    public int hashCode() {
      int result = hashCode;
      return result != 0 ? result : (hashCode = value != null ? value.hashCode() : 0);
    }

    public static final class Builder extends Message.Builder<Nested> {

      public FooBarBazEnum value;

      public Builder() {
      }

      public Builder(Nested message) {
        super(message);
        if (message == null) return;
        this.value = message.value;
      }

      public Builder value(FooBarBazEnum value) {
        this.value = value;
        return this;
      }

      @Override
      public Nested build() {
        return new Nested(this);
      }
    }
  }

  public enum FooBarBazEnum {
    @ProtoEnum(1)
    FOO,
    @ProtoEnum(2)
    BAR,
    @ProtoEnum(3)
    BAZ,
  }
}
