// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: roots.proto
package com.squareup.wire.protos.roots;

import com.squareup.wire.Extension;
import com.squareup.wire.WireField;
import java.util.Arrays;
import java.util.List;

public final class Ext_roots {
  public static final Extension<I, J> j = Extension.get(I.class,
      WireField.Label.OPTIONAL,
      "squareup.protos.roots.j",
      1000,
      "com.squareup.wire.protos.roots.J#ADAPTER");

  public static final List<Extension<?, ?>> EXTENSIONS = Arrays.<Extension<?, ?>>asList(
      j);

  private Ext_roots() {
  }
}
