// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/service_root.proto at 7:1
package com.squareup.wire.protos.roots;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import java.lang.Object;
import java.lang.Override;
import okio.ByteString;

public final class UnnecessaryResponse extends Message<UnnecessaryResponse> {
  public static final ProtoAdapter<UnnecessaryResponse> ADAPTER = ProtoAdapter.newMessageAdapter(UnnecessaryResponse.class);

  private static final long serialVersionUID = 0L;

  public UnnecessaryResponse() {
    this(ByteString.EMPTY);
  }

  public UnnecessaryResponse(ByteString unknownFields) {
    super(unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof UnnecessaryResponse;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<UnnecessaryResponse, Builder> {
    public Builder() {
    }

    @Override
    public UnnecessaryResponse build() {
      return new UnnecessaryResponse(buildUnknownFields());
    }
  }
}
