// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/redacted_test.proto
package com.squareup.wire.protos.redacted;

import com.google.protobuf.FieldOptions;
import com.squareup.wire.Extension;
import com.squareup.wire.WireField;
import java.lang.Boolean;

public final class Ext_redacted_test {
  public static final Extension<FieldOptions, Boolean> redacted = Extension.get(FieldOptions.class,
      WireField.Label.OPTIONAL,
      "squareup.protos.redacted_test.redacted",
      22200,
      "com.squareup.wire.ProtoAdapter#BOOL");

  public static final Extension<Redacted, RedactedExtension> extension = Extension.get(Redacted.class,
      WireField.Label.OPTIONAL,
      "squareup.protos.redacted_test.extension",
      10,
      "com.squareup.wire.protos.redacted.RedactedExtension#ADAPTER");

  private Ext_redacted_test() {
  }
}
