// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/foreign.proto
package com.squareup.wire.protos.foreign;

import com.google.protobuf.EnumValueOptions;
import com.google.protobuf.MessageOptions;
import com.squareup.wire.Extension;
import com.squareup.wire.TypeAdapter;
import java.lang.Boolean;

public final class Ext_foreign {
  public static final Extension<MessageOptions, ForeignMessage, ForeignMessage> foreign_message_option = Extension.optional(MessageOptions.class, 50005, ForeignMessage.ADAPTER);

  public static final Extension<EnumValueOptions, Boolean, Boolean> foreign_enum_value_option = Extension.optional(EnumValueOptions.class, 70002, TypeAdapter.BOOL);

  private Ext_foreign() {
  }
}
