// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/foreign.proto
package com.squareup.wire.protos.foreign;

import com.squareup.wire.ProtoEnum;

public enum ForeignEnum
    implements ProtoEnum {
  BAV(0),
  BAX(1),

  /**
   * Wire-generated value, do not access from application code.
   */
  __UNDEFINED__(UNDEFINED_VALUE);

  private final int value;

  private ForeignEnum(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
