// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.wire.no_immutable_copies.NoImmutableCopiesPayload in squareup/wire/no_immutable_copies.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package squareup.wire.no_immutable_copies

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

public class NoImmutableCopiesPayload(
  @field:WireField(
    tag = 1,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 0,
  )
  public val headers: Map<String, String> = emptyMap(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val footers: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NoImmutableCopiesPayload, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NoImmutableCopiesPayload) return false
    if (unknownFields != other.unknownFields) return false
    if (headers != other.headers) return false
    if (footers != other.footers) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + headers.hashCode()
      result = result * 37 + footers.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (headers.isNotEmpty()) result += """headers=$headers"""
    if (footers.isNotEmpty()) result += """footers=${sanitize(footers)}"""
    return result.joinToString(prefix = "NoImmutableCopiesPayload{", separator = ", ", postfix = "}")
  }

  public fun copy(
    headers: Map<String, String> = this.headers,
    footers: List<String> = this.footers,
    unknownFields: ByteString = this.unknownFields,
  ): NoImmutableCopiesPayload = NoImmutableCopiesPayload(headers, footers, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NoImmutableCopiesPayload> =
        object : ProtoAdapter<NoImmutableCopiesPayload>(
      FieldEncoding.LENGTH_DELIMITED, 
      NoImmutableCopiesPayload::class, 
      "type.googleapis.com/squareup.wire.no_immutable_copies.NoImmutableCopiesPayload", 
      PROTO_2, 
      null, 
      "squareup/wire/no_immutable_copies.proto"
    ) {
      private val headersAdapter: ProtoAdapter<Map<String, String>> by
          lazy { ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: NoImmutableCopiesPayload): Int {
        var size = value.unknownFields.size
        size += headersAdapter.encodedSizeWithTag(1, value.headers)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.footers)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NoImmutableCopiesPayload) {
        headersAdapter.encodeWithTag(writer, 1, value.headers)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.footers)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NoImmutableCopiesPayload) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.footers)
        headersAdapter.encodeWithTag(writer, 1, value.headers)
      }

      override fun decode(reader: ProtoReader): NoImmutableCopiesPayload {
        val headers = mutableMapOf<String, String>()
        val footers = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> headers.putAll(headersAdapter.decode(reader))
            2 -> footers.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return NoImmutableCopiesPayload(
          headers = headers,
          footers = footers,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NoImmutableCopiesPayload): NoImmutableCopiesPayload = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
