// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.custom_options.my_message_option_four in custom_options.proto
package com.squareup.wire.protos.custom_options

import kotlin.annotation.AnnotationRetention
import kotlin.annotation.AnnotationTarget
import kotlin.annotation.Retention
import kotlin.annotation.Target

@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.CLASS)
annotation class MyMessageOptionFour(
  val value: FooBar.FooBarBazEnum
)
