// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.custom_options.my_message_option_two in custom_options.proto
package com.squareup.wire.protos.custom_options

import kotlin.Float
import kotlin.annotation.AnnotationRetention
import kotlin.annotation.AnnotationTarget
import kotlin.annotation.Retention
import kotlin.annotation.Target

@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.CLASS)
annotation class MyMessageOptionTwo(
  val value: Float
)
