// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/edge_cases.proto at 20:1
package com.squareup.wire.protos.edgecases;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.TypeAdapter;
import java.io.IOException;
import java.lang.Override;

public final class NoFields extends Message<NoFields> {
  private static final long serialVersionUID = 0L;

  public static final TypeAdapter<NoFields> ADAPTER = new TypeAdapter.MessageAdapter<NoFields>() {
    @Override
    public NoFields read(ProtoReader reader) throws IOException {
      return NoFields.read(reader);
    }
  };

  public NoFields() {
    super("NoFields");
  }

  private NoFields(Builder builder) {
    this();
    setBuilder(builder);
  }

  @Override
  protected void visitFields(Message.Visitor visitor) {
    visitor.unknowns(this);
  }

  public static NoFields read(ProtoReader reader) throws IOException {
    Builder builder = new Builder();
    while (reader.hasNext()) {
      int tag = reader.nextTag();
      switch (tag) {
        default: builder.readUnknown(tag, reader); break;
      }
    }
    return builder.build();
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<NoFields> {
    public Builder() {
    }

    public Builder(NoFields message) {
      super(message);
    }

    @Override
    public NoFields build() {
      return new NoFields(this);
    }
  }
}
