// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/edge_cases.proto at 27:1
package com.squareup.wire.protos.edgecases;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.TypeAdapter;
import java.io.IOException;
import java.lang.Override;
import okio.ByteString;

public final class OneBytesField extends Message<OneBytesField> {
  private static final long serialVersionUID = 0L;

  public static final TypeAdapter<OneBytesField> ADAPTER = new TypeAdapter.MessageAdapter<OneBytesField>() {
    @Override
    public OneBytesField read(ProtoReader reader) throws IOException {
      return OneBytesField.read(reader);
    }
  };

  public static final ByteString DEFAULT_OPT_BYTES = ByteString.EMPTY;

  public final ByteString opt_bytes;

  public OneBytesField(ByteString opt_bytes) {
    super("OneBytesField");
    this.opt_bytes = opt_bytes;
  }

  private OneBytesField(Builder builder) {
    this(builder.opt_bytes);
    setBuilder(builder);
  }

  @Override
  protected void visitFields(Message.Visitor visitor) {
    visitor.value(1, "opt_bytes", opt_bytes, TypeAdapter.BYTES, false);
    visitor.unknowns(this);
  }

  public static OneBytesField read(ProtoReader reader) throws IOException {
    Builder builder = new Builder();
    while (reader.hasNext()) {
      int tag = reader.nextTag();
      switch (tag) {
        case 1: builder.opt_bytes = reader.value(TypeAdapter.BYTES); break;
        default: builder.readUnknown(tag, reader); break;
      }
    }
    return builder.build();
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<OneBytesField> {
    public ByteString opt_bytes;

    public Builder() {
    }

    public Builder(OneBytesField message) {
      super(message);
      if (message == null) return;
      this.opt_bytes = message.opt_bytes;
    }

    public Builder opt_bytes(ByteString opt_bytes) {
      this.opt_bytes = opt_bytes;
      return this;
    }

    @Override
    public OneBytesField build() {
      return new OneBytesField(this);
    }
  }
}
