// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.custom_options.enum_value_option in custom_options.proto
package com.squareup.wire.protos.custom_options;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This is a nice option! Apply it to your friendly enum constants.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface EnumValueOptionOption {
  int value();
}
