// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.EasterAnimal in easter.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package squareup

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class EasterAnimal(
  override val `value`: Int,
) : WireEnum {
  EASTER_ANIMAL_DEFAULT(0),
  BUNNY(1),
  HEN(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<EasterAnimal> = object : EnumAdapter<EasterAnimal>(
      EasterAnimal::class, 
      PROTO_3, 
      EasterAnimal.EASTER_ANIMAL_DEFAULT
    ) {
      override fun fromValue(`value`: Int): EasterAnimal? = EasterAnimal.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): EasterAnimal? = when (`value`) {
      0 -> EASTER_ANIMAL_DEFAULT
      1 -> BUNNY
      2 -> HEN
      else -> null
    }
  }
}
