// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.kotlin.unknownfields.NestedVersionOne in unknown_fields.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.squareup.wire.protos.kotlin.unknownfields

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmSynthetic
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import okio.ByteString

public class NestedVersionOne(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 0,
  )
  @JvmField
  public val i: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NestedVersionOne, NestedVersionOne.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.i = i
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NestedVersionOne) return false
    if (unknownFields != other.unknownFields) return false
    if (i != other.i) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (i?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (i != null) result += """i=$i"""
    return result.joinToString(prefix = "NestedVersionOne{", separator = ", ", postfix = "}")
  }

  public fun copy(i: Int? = this.i, unknownFields: ByteString = this.unknownFields): NestedVersionOne = NestedVersionOne(i, unknownFields)

  public class Builder : Message.Builder<NestedVersionOne, Builder>() {
    @JvmField
    public var i: Int? = null

    public fun i(i: Int?): Builder {
      this.i = i
      return this
    }

    override fun build(): NestedVersionOne = NestedVersionOne(
      i = i,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NestedVersionOne> = object : ProtoAdapter<NestedVersionOne>(
      FieldEncoding.LENGTH_DELIMITED, 
      NestedVersionOne::class, 
      "type.googleapis.com/squareup.protos.kotlin.unknownfields.NestedVersionOne", 
      PROTO_2, 
      null, 
      "unknown_fields.proto"
    ) {
      override fun encodedSize(`value`: NestedVersionOne): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.i)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NestedVersionOne) {
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.i)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NestedVersionOne) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.i)
      }

      override fun decode(reader: ProtoReader): NestedVersionOne {
        var i: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> i = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NestedVersionOne(
          i = i,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NestedVersionOne): NestedVersionOne = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L

    @JvmSynthetic
    public inline fun build(body: Builder.() -> Unit): NestedVersionOne = Builder().apply(body).build()
  }
}
