name: gradle-wrapper

on:
  pull_request:
    paths:
    - 'gradlew'
    - 'gradlew.bat'
    - 'gradle/wrapper/**'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6

